version: '3.1'

services:
  db:
    container_name: test_db
    image: mysql:5.7.39-debian
    environment:
      MYSQL_ROOT_PASSWORD: test
  web:
    container_name: test_web
    image: php:5.6-apache-jessie
    ports:
      - 80:80
  phpmyadmin:
    container_name:  test_phpmyadmin
    image: phpmyadmin:5.2.0-apache
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1